/**
 * RAG Improvement Service - P2#3
 * Création de blocs RAG et FAQ à partir des questions chatbot
 */

import { supabase } from '@/integrations/supabase/client';
import { safeMutation, safeQuery, safeInvoke } from '@/lib/safeQuery';
import { logDebug, logError } from '@/lib/logger';
import type { RAGContextType } from './rag-michu';

// ============ TYPES ============

export interface CreateBlockParams {
  queryId: string;
  title: string;
  content: string;
  contextType: RAGContextType;
  apporteurCode?: string;
  universCode?: string;
  roleCible?: string;
}

export interface CreateFaqParams {
  queryId: string;
  question: string;
  answer: string;
  contextType: RAGContextType;
  categoryId?: string;
  apporteurCode?: string;
  universCode?: string;
  roleCible?: string;
  linkedBlockIds?: string[];
}

export interface ImprovementResult {
  success: boolean;
  blockId?: string;
  faqId?: string;
  error?: string;
}

// ============ BLOCK CREATION ============

/**
 * Create a RAG block from a chatbot query
 * Inserts into guide_chunks table and triggers embedding generation
 */
export async function createBlockFromQuery(params: CreateBlockParams): Promise<ImprovementResult> {
  const { queryId, title, content, contextType, apporteurCode, universCode, roleCible } = params;

  logDebug('[RAG-IMPROVE] Creating block from query', queryId);

  // Map context type to block_type
  const blockTypeMap: Record<RAGContextType, string> = {
    apogee: 'apogee_guide',
    apporteurs: 'apporteur_guide',
    helpconfort: 'helpconfort_guide',
    metier: 'metier_guide',
    franchise: 'franchise_guide',
    documents: 'document',
    auto: 'apogee_guide',
  };

  const blockType = blockTypeMap[contextType] || 'apogee_guide';
  const blockId = crypto.randomUUID();
  const slug = `faq-${blockId.slice(0, 8)}`;

  // Insert into guide_chunks (simple chunk without embedding for now)
  // The embedding will be generated by the index-document edge function
  const chunkResult = await safeMutation(
    supabase.from('guide_chunks').insert([{
      block_id: blockId,
      block_type: blockType,
      block_title: title,
      block_slug: slug,
      chunk_text: content,
      chunk_index: 0,
      context_type: contextType as RAGContextType,
      embedding: [], // Will be populated by edge function
      metadata: {
        source: contextType,
        family: contextType,
        apporteur_code: apporteurCode || null,
        univers_code: universCode || null,
        role_cible: roleCible || null,
        created_from_query: queryId,
        source_type: 'faq_improvement',
      },
    }]),
    'RAG_IMPROVE_CREATE_BLOCK'
  );

  if (!chunkResult.success) {
    logError('rag-improvement', 'Failed to create block', chunkResult.error);
    return { success: false, error: chunkResult.error?.message || 'Failed to create block' };
  }

  // Update chatbot_queries with improvement_block_id
  const updateResult = await safeMutation(
    supabase
      .from('chatbot_queries')
      .update({ improvement_block_id: blockId })
      .eq('id', queryId),
    'RAG_IMPROVE_UPDATE_QUERY'
  );

  if (!updateResult.success) {
    logError('rag-improvement', 'Failed to update query with block id', updateResult.error);
    // Non-critical, continue
  }

  // Trigger embedding generation via edge function
  const embedResult = await safeInvoke(
    supabase.functions.invoke('generate-embeddings', {
      body: { blockId, text: content },
    }),
    'RAG_IMPROVE_GENERATE_EMBEDDING'
  );

  if (!embedResult.success) {
    logError('rag-improvement', 'Failed to generate embedding (non-critical)', embedResult.error);
    // Non-critical - block is created, embedding can be regenerated later
  }

  logDebug('[RAG-IMPROVE] Block created successfully', blockId);
  return { success: true, blockId };
}

// ============ FAQ CREATION ============

/**
 * Create a FAQ item from a chatbot query
 */
export async function createFaqFromQuery(params: CreateFaqParams): Promise<ImprovementResult> {
  const {
    queryId,
    question,
    answer,
    contextType,
    categoryId,
    apporteurCode,
    universCode,
    roleCible,
    linkedBlockIds,
  } = params;

  logDebug('[RAG-IMPROVE] Creating FAQ from query', queryId);

  const insertData: Record<string, unknown> = {
    question,
    answer,
    context_type: contextType,
    apporteur_code: apporteurCode || null,
    univers_code: universCode || null,
    role_cible: roleCible || null,
    linked_block_ids: linkedBlockIds || [],
    created_from_query_id: queryId,
    is_published: true,
  };

  if (categoryId) {
    insertData.category_id = categoryId;
  }

  const result = await safeMutation<{ id: string }[]>(
    supabase.from('faq_items').insert(insertData as any).select('id'),
    'RAG_IMPROVE_CREATE_FAQ'
  );

  if (!result.success) {
    logError('rag-improvement', 'Failed to create FAQ', result.error);
    return { success: false, error: result.error?.message || 'Failed to create FAQ' };
  }

  const faqId = result.data?.[0]?.id;
  logDebug('[RAG-IMPROVE] FAQ created successfully', faqId);
  return { success: true, faqId };
}

// ============ COMBINED IMPROVEMENT ============

/**
 * Create both block and FAQ from a query (if requested)
 */
export async function improveFromQuery(params: {
  queryId: string;
  title: string;
  content: string;
  question: string;
  answer: string;
  contextType: RAGContextType;
  categoryId?: string;
  apporteurCode?: string;
  universCode?: string;
  roleCible?: string;
  createBlock: boolean;
  createFaq: boolean;
}): Promise<ImprovementResult> {
  const results: ImprovementResult = { success: true };

  if (params.createBlock) {
    const blockResult = await createBlockFromQuery({
      queryId: params.queryId,
      title: params.title,
      content: params.content,
      contextType: params.contextType,
      apporteurCode: params.apporteurCode,
      universCode: params.universCode,
      roleCible: params.roleCible,
    });

    if (!blockResult.success) {
      return blockResult;
    }
    results.blockId = blockResult.blockId;
  }

  if (params.createFaq) {
    const faqResult = await createFaqFromQuery({
      queryId: params.queryId,
      question: params.question,
      answer: params.answer,
      contextType: params.contextType,
      categoryId: params.categoryId,
      apporteurCode: params.apporteurCode,
      universCode: params.universCode,
      roleCible: params.roleCible,
      linkedBlockIds: results.blockId ? [results.blockId] : [],
    });

    if (!faqResult.success) {
      return faqResult;
    }
    results.faqId = faqResult.faqId;
  }

  return results;
}

// ============ FAQ QUERIES ============

export interface FaqItem {
  id: string;
  question: string;
  answer: string;
  context_type: string;
  category_id: string | null;
  apporteur_code: string | null;
  univers_code: string | null;
  role_cible: string | null;
  linked_block_ids: string[] | null;
  created_from_query_id: string | null;
  is_published: boolean;
  display_order: number;
  created_at: string;
  updated_at: string;
  category?: { id: string; label: string; slug: string } | null;
}

export interface FaqCategory {
  id: string;
  label: string;
  slug: string;
  display_order: number;
}

/**
 * Get all FAQ categories
 */
export async function getFaqCategories(): Promise<FaqCategory[]> {
  const result = await safeQuery<FaqCategory[]>(
    supabase
      .from('faq_categories')
      .select('*')
      .order('display_order', { ascending: true }),
    'RAG_FAQ_LOAD_CATEGORIES'
  );

  return result.success ? (result.data || []) : [];
}

/**
 * Get FAQ items with optional filters
 */
export async function getFaqItems(filters?: {
  contextType?: string;
  categoryId?: string;
  publishedOnly?: boolean;
}): Promise<FaqItem[]> {
  let query = supabase
    .from('faq_items')
    .select('*, category:faq_categories(id, label, slug)')
    .order('display_order', { ascending: true });

  if (filters?.contextType && filters.contextType !== 'all') {
    query = query.eq('context_type', filters.contextType as RAGContextType);
  }

  if (filters?.categoryId) {
    query = query.eq('category_id', filters.categoryId);
  }

  if (filters?.publishedOnly !== false) {
    query = query.eq('is_published', true);
  }

  const result = await safeQuery<FaqItem[]>(query, 'RAG_FAQ_LOAD_ITEMS');
  return result.success ? (result.data || []) : [];
}

// ============ STATS ============

export interface FaqStats {
  total: number;
  fromQueries: number;
  byContext: Record<string, number>;
}

/**
 * Get FAQ statistics for monitoring
 */
export async function getFaqStats(): Promise<FaqStats> {
  const result = await safeQuery<{ context_type: string; created_from_query_id: string | null }[]>(
    supabase.from('faq_items').select('context_type, created_from_query_id'),
    'RAG_FAQ_LOAD_STATS'
  );

  if (!result.success || !result.data) {
    return { total: 0, fromQueries: 0, byContext: {} };
  }

  const items = result.data;
  const byContext: Record<string, number> = {};

  for (const item of items) {
    const ctx = item.context_type || 'autre';
    byContext[ctx] = (byContext[ctx] || 0) + 1;
  }

  return {
    total: items.length,
    fromQueries: items.filter(i => i.created_from_query_id).length,
    byContext,
  };
}

/**
 * Get count of improved queries (with improvement_block_id)
 */
export async function getImprovedQueriesCount(): Promise<number> {
  const result = await safeQuery<{ count: number }[]>(
    supabase
      .from('chatbot_queries')
      .select('id', { count: 'exact', head: true })
      .not('improvement_block_id', 'is', null),
    'RAG_IMPROVED_QUERIES_COUNT'
  );

  // For count queries, the count is in the response headers
  // Using a workaround since safeQuery doesn't expose count
  const countResult = await supabase
    .from('chatbot_queries')
    .select('id', { count: 'exact', head: true })
    .not('improvement_block_id', 'is', null);

  return countResult.count || 0;
}
