services:
  apogeedemo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_PUBLISHABLE_KEY=${VITE_SUPABASE_PUBLISHABLE_KEY}
        - VITE_SUPABASE_PROJECT_ID=${VITE_SUPABASE_PROJECT_ID}
    container_name: helpconfort-services
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apogeedemo.entrypoints=https"
      - "traefik.http.routers.apogeedemo.rule=Host(`apogee.demo.hb-digitals.fr`) || Host(`suivi.helpconfort.services`) || Host(`helpconfort.services`)"
      - "traefik.http.routers.apogeedemo.tls=true"
      - "traefik.http.routers.apogeedemo.tls.certresolver=letsencrypt"
      - "traefik.http.services.apogeedemo.loadbalancer.server.port=80"
      - "traefik.http.routers.apogeedemo.middlewares=secure-headers@file"

networks:
  web:
    external: true
