import { 
  BookOpen, FileText, FolderOpen, BarChart3, ListTodo, Tv,
  MessageSquare, Network, Users, Database, Settings, LucideIcon,
  PieChart, Coins, LifeBuoy, Headphones, GraduationCap, Kanban, Activity,
  HelpCircle, Calendar, UserCog, Briefcase, Inbox, Building2, GitCompare,
  MessagesSquare, Wrench, Brain, Car, Radar, ToggleLeft, LayoutDashboard, LineChart
} from 'lucide-react';
import { ROUTES } from './routes';
import { ModuleKey } from '@/types/modules';
import { SCOPE_SLUGS } from './scopeRegistry';

export interface DashboardTile {
  id: string;
  title: string;
  description: string;
  icon: LucideIcon;
  route: string;
  scopeSlug: string;
  color: 'primary' | 'accent';
  group: 'help_academy' | 'pilotage' | 'rh' | 'support' | 'projects' | 'franchiseur' | 'admin' | 'communication' | 'technicien';
  requiresAdmin?: boolean;
  requiresFranchisor?: boolean; // N3+ (franchisor_user)
  requiresModule?: ModuleKey; // Requires specific module to be enabled
  requiresModuleOption?: string; // Requires specific module option (e.g., 'coffre' for rh_parc.coffre)
  requiresModuleOptions?: string[]; // OR logic - at least one option required
  featureFlagKey?: string; // Clé du feature flag global (ex: 'pilotage.actions-mener')
  badge?: string;
  isDisabled?: boolean; // Tuile grisée "Bientôt disponible"
}

export const DASHBOARD_TILES: DashboardTile[] = [
  // Help Academy
  {
    id: 'GUIDE_APOGEE',
    title: 'Guide Apogée',
    description: 'Guide complet pour maîtriser le logiciel Apogée',
    icon: BookOpen,
    route: ROUTES.academy.apogee,
    scopeSlug: SCOPE_SLUGS.APOGEE,
    color: 'primary',
    group: 'help_academy',
    requiresModule: 'help_academy',
  },
  {
    id: 'GUIDE_APPORTEURS',
    title: 'Guide Apporteurs',
    description: 'Ressources pour les apporteurs d\'affaires',
    icon: FileText,
    route: ROUTES.academy.apporteurs,
    scopeSlug: SCOPE_SLUGS.APPORTEURS,
    color: 'primary',
    group: 'help_academy',
    requiresModule: 'help_academy',
  },
  {
    id: 'BASE_DOCUMENTAIRE',
    title: 'Base Documentaire',
    description: 'Documents et ressources HelpConfort',
    icon: FolderOpen,
    route: ROUTES.academy.documents,
    scopeSlug: SCOPE_SLUGS.BASE_DOCUMENTAIRE,
    color: 'primary',
    group: 'help_academy',
    requiresModule: 'help_academy',
  },
  // Pilotage Agence
  {
    id: 'STATISTIQUES_HUB',
    title: 'Statistiques',
    description: 'Accès aux indicateurs et KPI de votre agence',
    icon: PieChart,
    route: ROUTES.agency.statsHub,
    scopeSlug: SCOPE_SLUGS.MES_INDICATEURS,
    color: 'accent',
    group: 'pilotage',
    requiresModule: 'pilotage_agence',
  },
  {
    id: 'ACTIONS_A_MENER',
    title: 'Actions à Mener',
    description: 'Suivi des actions et tâches en cours',
    icon: ListTodo,
    route: ROUTES.agency.actions,
    scopeSlug: SCOPE_SLUGS.ACTIONS_A_MENER,
    color: 'accent',
    group: 'pilotage',
    requiresModule: 'pilotage_agence',
    featureFlagKey: 'pilotage.actions-mener',
  },
  {
    id: 'VEILLE_APPORTEURS',
    title: 'Veille Apporteurs',
    description: 'Suivi performance et alertes apporteurs',
    icon: Radar,
    route: ROUTES.agency.veilleApporteurs,
    scopeSlug: SCOPE_SLUGS.MES_INDICATEURS,
    color: 'accent',
    group: 'pilotage',
    requiresModule: 'pilotage_agence',
  },
  {
    id: 'MAINTENANCE_PREVENTIVE',
    title: 'Maintenance préventive',
    description: 'Véhicules, matériel et EPI',
    icon: Car,
    route: ROUTES.agency.maintenance,
    scopeSlug: SCOPE_SLUGS.ACTIONS_A_MENER,
    color: 'accent',
    group: 'pilotage',
    requiresModule: 'pilotage_agence',
  },
  {
    id: 'DIFFUSION',
    title: 'Diffusion',
    description: 'Mode affichage TV agence',
    icon: Tv,
    route: ROUTES.agency.diffusion,
    scopeSlug: SCOPE_SLUGS.DIFFUSION,
    color: 'accent',
    group: 'pilotage',
    requiresModule: 'pilotage_agence',
    featureFlagKey: 'pilotage.diffusion',
    badge: 'En cours',
  },
  {
    id: 'VALIDATION_PLANNINGS',
    title: 'Validation plannings',
    description: 'Validation des plannings hebdomadaires',
    icon: Calendar,
    route: ROUTES.agency.rhTech,
    scopeSlug: SCOPE_SLUGS.RH_TECH,
    color: 'accent',
    group: 'rh',
    requiresModule: 'rh',
    requiresModuleOptions: ['rh_viewer', 'rh_admin'],
    featureFlagKey: 'rh.validation-plannings',
    badge: 'Bientôt',
    isDisabled: true,
  },
  {
    id: 'MON_EQUIPE',
    title: 'Mon équipe',
    description: 'Collaborateurs, documents RH et bulletins de salaire',
    icon: UserCog,
    route: ROUTES.rh.equipe,
    scopeSlug: SCOPE_SLUGS.MON_EQUIPE,
    color: 'accent',
    group: 'rh',
    requiresModule: 'rh',
    requiresModuleOptions: ['rh_viewer', 'rh_admin'],
  },
  {
    id: 'MON_COFFRE_RH',
    title: 'Mon Coffre RH',
    description: 'Mes documents RH personnels',
    icon: Briefcase,
    route: ROUTES.rh.coffre,
    scopeSlug: SCOPE_SLUGS.MON_COFFRE_RH,
    color: 'accent',
    group: 'rh',
    requiresModule: 'rh',
    requiresModuleOptions: ['coffre', 'rh_viewer', 'rh_admin'],
  },
  {
    id: 'DEMANDE_RH',
    title: 'Demande RH',
    description: 'Soumettre une demande RH',
    icon: Inbox,
    route: ROUTES.rh.demande,
    scopeSlug: SCOPE_SLUGS.MON_COFFRE_RH,
    color: 'accent',
    group: 'rh',
    requiresModule: 'rh',
    requiresModuleOptions: ['coffre', 'rh_viewer', 'rh_admin'],
  },
  {
    id: 'DEMANDES_RH',
    title: 'Demandes RH',
    description: 'Traitement des demandes de documents',
    icon: Inbox,
    route: ROUTES.rh.demandes,
    scopeSlug: SCOPE_SLUGS.DEMANDES_RH,
    color: 'accent',
    group: 'rh', // Groupe dédié RH, indépendant de pilotage
    requiresModule: 'rh',
    requiresModuleOptions: ['rh_viewer', 'rh_admin'], // OR logic - l'une ou l'autre
  },
  // Support
  {
    id: 'SUPPORT',
    title: 'Support',
    description: 'Chat IA et assistance en ligne',
    icon: HelpCircle,
    route: ROUTES.support.index,
    scopeSlug: SCOPE_SLUGS.MES_DEMANDES,
    color: 'primary',
    group: 'support',
  },
  {
    id: 'OUVRIR_TICKET',
    title: 'Ouvrir un ticket',
    description: 'Créer une nouvelle demande de support',
    icon: LifeBuoy,
    route: ROUTES.support.userTickets,
    scopeSlug: SCOPE_SLUGS.MES_DEMANDES,
    color: 'primary',
    group: 'support',
  },
  {
    id: 'CONSOLE_SUPPORT',
    title: 'Console support',
    description: 'Gestion des tickets et demandes utilisateurs',
    icon: Headphones,
    route: ROUTES.support.console,
    scopeSlug: SCOPE_SLUGS.SUPPORT_TICKETS,
    color: 'accent',
    group: 'support',
    // F-NAV-1: requiresSupport supprimé - filtrage via canAccessSupportConsoleUI uniquement
  },
  // Communication / Messagerie
  {
    id: 'MESSAGING',
    title: 'Messages',
    description: 'Discussions internes et groupes',
    icon: MessagesSquare,
    route: ROUTES.messages,
    scopeSlug: SCOPE_SLUGS.MESSAGING,
    color: 'primary',
    group: 'communication',
  },
  // Gestion de Projet
  {
    id: 'PROJET_INDEX',
    title: 'Gestion de Projet',
    description: 'Kanban et suivi des tickets développement',
    icon: Kanban,
    route: ROUTES.projects.index,
    scopeSlug: SCOPE_SLUGS.APOGEE_TICKETS,
    color: 'accent',
    group: 'projects',
    requiresModule: 'apogee_tickets',
  },
  // Espace Technicien
  {
    id: 'TECH_APP',
    title: 'APP',
    description: 'Interventions et relevés techniques',
    icon: Wrench,
    route: ROUTES.agency.techInterventions,
    scopeSlug: SCOPE_SLUGS.RH_TECH,
    color: 'accent',
    group: 'technicien',
    requiresModule: 'pilotage_agence', // P2: Filtre module pour cacher aux N0 sans module
  },
  // Franchiseur
  {
    id: 'RESEAU_FRANCHISEUR',
    title: 'Dashboard Réseau',
    description: 'Pilotage multi-agences et KPIs réseau',
    icon: Network,
    route: ROUTES.reseau.dashboard,
    scopeSlug: SCOPE_SLUGS.FRANCHISEUR_DASHBOARD,
    color: 'accent',
    group: 'franchiseur',
  },
  {
    id: 'FRANCHISEUR_AGENCES',
    title: 'Agences',
    description: 'Gestion des agences du réseau',
    icon: Building2,
    route: ROUTES.reseau.agences,
    scopeSlug: SCOPE_SLUGS.FRANCHISEUR_AGENCIES,
    color: 'accent',
    group: 'franchiseur',
  },
  {
    id: 'FRANCHISEUR_USERS',
    title: 'Utilisateurs Réseau',
    description: 'Gestion des utilisateurs du réseau',
    icon: Users,
    route: ROUTES.reseau.users,
    scopeSlug: SCOPE_SLUGS.FRANCHISEUR_AGENCIES,
    color: 'accent',
    group: 'franchiseur',
  },
  {
    id: 'FRANCHISEUR_STATS',
    title: 'Statistiques Réseau',
    description: 'Matrices de performance multi-agences',
    icon: PieChart,
    route: ROUTES.reseau.tableaux,
    scopeSlug: SCOPE_SLUGS.FRANCHISEUR_KPI,
    color: 'accent',
    group: 'franchiseur',
  },
  {
    id: 'FRANCHISEUR_PERIODES',
    title: 'Périodes',
    description: 'Comparaison des performances entre agences',
    icon: GitCompare,
    route: ROUTES.reseau.periodes,
    scopeSlug: SCOPE_SLUGS.FRANCHISEUR_KPI,
    color: 'accent',
    group: 'franchiseur',
  },
  {
    id: 'FRANCHISEUR_COMPARATIF',
    title: 'Comparatif',
    description: 'Tableau comparatif KPI par agence',
    icon: BarChart3,
    route: ROUTES.reseau.comparatif,
    scopeSlug: SCOPE_SLUGS.FRANCHISEUR_KPI,
    color: 'accent',
    group: 'franchiseur',
  },
  {
    id: 'FRANCHISEUR_ROYALTIES',
    title: 'Redevances',
    description: 'Calcul et suivi mensuel des redevances',
    icon: Coins,
    route: ROUTES.reseau.redevances,
    scopeSlug: SCOPE_SLUGS.FRANCHISEUR_ROYALTIES,
    color: 'accent',
    group: 'franchiseur',
    badge: 'En cours',
  },
  // Administration
  {
    id: 'ADMIN_USERS',
    title: 'Utilisateurs',
    description: 'Gestion des comptes utilisateurs',
    icon: Users,
    route: ROUTES.admin.users,
    scopeSlug: SCOPE_SLUGS.ADMIN_USERS,
    color: 'primary',
    group: 'admin',
    requiresFranchisor: true, // N3+ can manage users
  },
  {
    id: 'ADMIN_ANNOUNCEMENTS',
    title: 'Annonces',
    description: 'Annonces prioritaires réseau',
    icon: MessageSquare,
    route: ROUTES.admin.announcements,
    scopeSlug: SCOPE_SLUGS.ADMIN_SETTINGS,
    color: 'primary',
    group: 'admin',
    requiresAdmin: true,
  },
  {
    id: 'ADMIN_BACKUP',
    title: 'Sauvegarde',
    description: 'Import et export des données',
    icon: Database,
    route: ROUTES.admin.backup,
    scopeSlug: SCOPE_SLUGS.ADMIN_BACKUP,
    color: 'primary',
    group: 'admin',
    requiresAdmin: true,
  },
  {
    id: 'ADMIN_SETTINGS',
    title: 'Paramètres',
    description: 'Configuration du système',
    icon: Settings,
    route: ROUTES.admin.index,
    scopeSlug: SCOPE_SLUGS.ADMIN_SETTINGS,
    color: 'primary',
    group: 'admin',
    requiresAdmin: true,
  },
  {
    id: 'ADMIN_SYSTEM_HEALTH',
    title: 'Santé Système',
    description: 'Monitoring et état des services',
    icon: Activity,
    route: ROUTES.admin.systemHealth,
    scopeSlug: SCOPE_SLUGS.ADMIN_SETTINGS,
    color: 'primary',
    group: 'admin',
    requiresAdmin: true,
  },
  {
    id: 'ADMIN_HELPI',
    title: 'Helpi',
    description: 'Moteur de connaissances IA unifié',
    icon: Brain,
    route: ROUTES.admin.helpi,
    scopeSlug: SCOPE_SLUGS.ADMIN_SETTINGS,
    color: 'primary',
    group: 'admin',
    requiresAdmin: true,
  },
  {
    id: 'ADMIN_FEATURE_FLAGS',
    title: 'Feature Flags',
    description: 'Activation des fonctionnalités',
    icon: ToggleLeft,
    route: ROUTES.admin.featureFlags,
    scopeSlug: SCOPE_SLUGS.ADMIN_SETTINGS,
    color: 'primary',
    group: 'admin',
    requiresAdmin: true,
  },
  {
    id: 'ADMIN_WIDGETS',
    title: 'Widgets',
    description: 'Configuration des widgets dashboard',
    icon: LayoutDashboard,
    route: ROUTES.admin.widgets,
    scopeSlug: SCOPE_SLUGS.ADMIN_SETTINGS,
    color: 'primary',
    group: 'admin',
    requiresAdmin: true,
  },
  {
    id: 'FRANCHISEUR_GRAPHIQUES',
    title: 'Graphiques',
    description: 'Visualisations graphiques du réseau',
    icon: LineChart,
    route: ROUTES.reseau.graphiques,
    scopeSlug: SCOPE_SLUGS.FRANCHISEUR_KPI,
    color: 'accent',
    group: 'franchiseur',
  },
];

export const DASHBOARD_GROUPS = {
  help_academy: {
    title: 'Help! Academy',
    icon: GraduationCap,
    colorClass: 'text-primary',
    indexUrl: ROUTES.academy.index,
  },
  pilotage: {
    title: 'Mon Agence',
    icon: Building2,
    colorClass: 'text-accent',
    indexUrl: ROUTES.agency.index,
  },
  rh: {
    title: 'Mon Espace RH',
    icon: Briefcase,
    colorClass: 'text-helpconfort-blue',
    indexUrl: ROUTES.rh.index,
  },
  support: {
    title: 'Support',
    icon: Headphones,
    colorClass: 'text-primary',
    indexUrl: ROUTES.support.index,
  },
  communication: {
    title: 'Communication',
    icon: MessagesSquare,
    colorClass: 'text-helpconfort-blue',
    indexUrl: ROUTES.messages,
  },
  projects: {
    title: 'Gestion de Projet',
    icon: Kanban,
    colorClass: 'text-accent',
    indexUrl: ROUTES.projects.index,
  },
  franchiseur: {
    title: 'Espace Franchiseur',
    icon: Network,
    colorClass: 'text-accent',
    indexUrl: ROUTES.reseau.index,
  },
  admin: {
    title: 'Administration',
    icon: Settings,
    colorClass: 'text-destructive',
    indexUrl: ROUTES.admin.index,
  },
  technicien: {
    title: 'Espace Technicien',
    icon: Wrench,
    colorClass: 'text-helpconfort-orange',
    indexUrl: ROUTES.agency.techInterventions,
  },
} as const;
