
ALTER TABLE public.collaborators
  ADD COLUMN IF NOT EXISTS work_start TEXT DEFAULT '07:00',
  ADD COLUMN IF NOT EXISTS work_end TEXT DEFAULT '18:00',
  ADD COLUMN IF NOT EXISTS lunch_start TEXT DEFAULT '12:00',
  ADD COLUMN IF NOT EXISTS lunch_end TEXT DEFAULT '13:00',
  ADD COLUMN IF NOT EXISTS work_days INTEGER[] DEFAULT '{1,2,3,4,5}';
